/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
import java.util.Random;
public class OrderTaker extends javax.swing.JFrame {

    /**
     * Creates new form OrderTaker
     */
    public OrderTaker() {
        initComponents();
       
    }

    double total;
    double entree;
    double side;
    double drink;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        HotDog = new javax.swing.JButton();
        Burger = new javax.swing.JButton();
        PolishSausage = new javax.swing.JButton();
        OnionRings = new javax.swing.JButton();
        Fries = new javax.swing.JButton();
        CheeseSauce = new javax.swing.JButton();
        Soda = new javax.swing.JButton();
        Water = new javax.swing.JButton();
        MilkShake = new javax.swing.JButton();
        Greeting = new javax.swing.JButton();
        Manager = new javax.swing.JButton();
        Employee = new javax.swing.JButton();
        Customer = new javax.swing.JButton();
        Military = new javax.swing.JButton();
        DiscountEnter = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        Display = new javax.swing.JButton();
        Greeting1 = new javax.swing.JButton();
        DisplayBox = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        quit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        display.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setMargin(new java.awt.Insets(15, 15, 15, 15));
        display.setName(""); // NOI18N
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 400));
        jPanel1.setLayout(new java.awt.GridLayout(4, 0));

        HotDog.setText("Hot Dog");
        HotDog.setToolTipText("");
        HotDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreeButtonPressed(evt);
            }
        });
        jPanel1.add(HotDog);

        Burger.setText("Burger");
        Burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreeButtonPressed(evt);
            }
        });
        jPanel1.add(Burger);

        PolishSausage.setText("Polish Sausage");
        PolishSausage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreeButtonPressed(evt);
            }
        });
        jPanel1.add(PolishSausage);

        OnionRings.setText("Onion Rings");
        OnionRings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideButtonPressed(evt);
            }
        });
        jPanel1.add(OnionRings);

        Fries.setText("Fries");
        Fries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideButtonPressed(evt);
            }
        });
        jPanel1.add(Fries);

        CheeseSauce.setText("Cheese Sauce");
        CheeseSauce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideButtonPressed(evt);
            }
        });
        jPanel1.add(CheeseSauce);

        Soda.setText("Soda");
        Soda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkButtonPressed(evt);
            }
        });
        jPanel1.add(Soda);

        Water.setText("Water");
        Water.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkButtonPressed(evt);
            }
        });
        jPanel1.add(Water);

        MilkShake.setText("MilkShake");
        MilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkButtonPressed(evt);
            }
        });
        jPanel1.add(MilkShake);

        Greeting.setText("Greeting");
        Greeting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreetingButtonPressed(evt);
            }
        });
        jPanel1.add(Greeting);

        Manager.setText("Manager");
        Manager.setEnabled(false);
        Manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerButtonPressed(evt);
            }
        });
        jPanel1.add(Manager);

        Employee.setText("Employee");
        Employee.setEnabled(false);
        Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeButtonPressed(evt);
            }
        });
        jPanel1.add(Employee);

        Customer.setText("Customer");
        Customer.setEnabled(false);
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerorderButtonPressed(evt);
            }
        });
        jPanel1.add(Customer);

        Military.setText("Military");
        Military.setEnabled(false);
        Military.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilitaryorderButtonPressed(evt);
            }
        });
        jPanel1.add(Military);

        DiscountEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscountEnterActionPerformed(evt);
            }
        });
        jPanel1.add(DiscountEnter);

        Clear.setText("C");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonPressed(evt);
            }
        });
        jPanel1.add(Clear);

        Display.setText("Display");
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButtonPressed(evt);
            }
        });
        jPanel1.add(Display);

        Greeting1.setText("Final Cost");
        Greeting1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalCostPressed(evt);
            }
        });
        jPanel1.add(Greeting1);

        DisplayBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DisplayBox.setMargin(new java.awt.Insets(4, 4, 4, 4));
        DisplayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBoxActionPerformed(evt);
            }
        });
        jPanel1.add(DisplayBox);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jMenu1.add(quit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jMenu2.add(About);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, "Name:Eugene, Logan, and Quinn.  Created in Fall 2020");
    }//GEN-LAST:event_AboutActionPerformed

    private void EntreeButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntreeButtonPressed
        // TODO add your handling code here:
        total += 5.00;
         String str = String.valueOf(total);
        DisplayBox.setText(str);
        
    }//GEN-LAST:event_EntreeButtonPressed

    private void sideButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideButtonPressed
        // TODO add your handling code here:
        total += 3.00;
        String str = String.valueOf(total);
        DisplayBox.setText(str);
    }//GEN-LAST:event_sideButtonPressed

    private void drinkButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkButtonPressed
        // TODO add your handling code here:
        total += 2.00;
        String str = String.valueOf(total);
        DisplayBox.setText(str);
    }//GEN-LAST:event_drinkButtonPressed

    private void DisplayButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButtonPressed
        // TODO add your handling code here:
         String TotalStr = String.valueOf(total);
        
        DisplayBox.setText("Current Cost is $ " + TotalStr);

        
    }//GEN-LAST:event_DisplayButtonPressed

    private void GreetingButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreetingButtonPressed
        // TODO add your handling code here:
       Random rand = new Random();
        int randInt = rand.nextInt(4);
        String greeting = "";
        greeting = "Hello! and welcome to Generic Foods ";
        if (randInt == 2) {
            greeting = "Welcome!!";
        }
        else if (randInt == 3) {
            greeting = "What would you like?";
        }
        
        
        String str = String.valueOf(greeting);
        display.setText(str);
        
        
    }//GEN-LAST:event_GreetingButtonPressed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
        
        

    }//GEN-LAST:event_displayActionPerformed

    private void FinalCostPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalCostPressed
        // TODO add your handling code here:
        String TotalStr = String.valueOf(total);
        
        DisplayBox.setText("Final Cost is $ " + TotalStr);
        HotDog.setEnabled(false);
        Burger.setEnabled(false);
        PolishSausage.setEnabled(false);
        OnionRings.setEnabled(false);
        Fries.setEnabled(false);
        CheeseSauce.setEnabled(false);
        Soda.setEnabled(false);
        Water.setEnabled(false);
        MilkShake.setEnabled(false);
        Manager.setEnabled(true);
        Employee.setEnabled(true);
        Customer.setEnabled(true);
        Military.setEnabled(true);
       
                
        
    }//GEN-LAST:event_FinalCostPressed

    private void ClearButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonPressed
        // TODO add your handling code here:
        total = 0;
        DisplayBox.setText("");
        HotDog.setEnabled(true);
        Burger.setEnabled(true);
        PolishSausage.setEnabled(true);
        OnionRings.setEnabled(true);
        Fries.setEnabled(true);
        CheeseSauce.setEnabled(true);
        Soda.setEnabled(true);
        Water.setEnabled(true);
        MilkShake.setEnabled(true);
        // re enable buttons after clearing values
        
        //re disabled buttons after clearing
         Manager.setEnabled(false);
        Employee.setEnabled(false);
        Customer.setEnabled(false);
        Military.setEnabled(false);
    }//GEN-LAST:event_ClearButtonPressed

    private void DisplayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayBoxActionPerformed

    private void MilitaryorderButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilitaryorderButtonPressed
        // TODO add your handling code here:
        Manager.setEnabled(false);
        Employee.setEnabled(false);
        Customer.setEnabled(false);
        Military.setEnabled(false);
    }//GEN-LAST:event_MilitaryorderButtonPressed

    private void CustomerorderButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerorderButtonPressed
        // TODO add your handling code here:
       Manager.setEnabled(false);
        Employee.setEnabled(false);
        Customer.setEnabled(false);
        Military.setEnabled(false);
        
    }//GEN-LAST:event_CustomerorderButtonPressed

    private void DiscountEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscountEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiscountEnterActionPerformed

    private void ManagerButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerButtonPressed
        // TODO add your handling code here:
        Manager.setEnabled(false);
        Employee.setEnabled(false);
        Customer.setEnabled(false);
        Military.setEnabled(false);
    }//GEN-LAST:event_ManagerButtonPressed

    private void EmployeeButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeButtonPressed
        // TODO add your handling code here:
        Manager.setEnabled(false);
        Employee.setEnabled(false);
        Customer.setEnabled(false);
        Military.setEnabled(false);
    }//GEN-LAST:event_EmployeeButtonPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
              
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderTaker().setVisible(true);
            }
        });

        double total;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JButton Burger;
    private javax.swing.JButton CheeseSauce;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Customer;
    private javax.swing.JTextField DiscountEnter;
    private javax.swing.JButton Display;
    private javax.swing.JTextField DisplayBox;
    private javax.swing.JButton Employee;
    private javax.swing.JButton Fries;
    private javax.swing.JButton Greeting;
    private javax.swing.JButton Greeting1;
    private javax.swing.JButton HotDog;
    private javax.swing.JButton Manager;
    private javax.swing.JButton Military;
    private javax.swing.JButton MilkShake;
    private javax.swing.JButton OnionRings;
    private javax.swing.JButton PolishSausage;
    private javax.swing.JButton Soda;
    private javax.swing.JButton Water;
    private javax.swing.JTextField display;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem quit;
    // End of variables declaration//GEN-END:variables

    private double result;
    private char operation;
    private String disp;

   

    private void allClear() {
        result = 0.0;
        operation = '+';
        disp = "";
    }


    private void onButtonPressed(javax.swing.JButton which) {

        String buttonText = which.getText();
        
    }

}
